# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The World To Come
email: theworldtocome1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Official Web Site For The World To Come
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://twtcband.com" # the base hostname & protocol for your site
twitter_username: TWTCMUSIC
#github_username:  Lamencha
encoding: utf-8
# Build settings
markdown: kramdown
